// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwjVRy901WuPDsh05KboY9ioJlxq9Jiwg',
    appId: '1:250155716405:web:1ad661e18d43d2704e467c',
    messagingSenderId: '250155716405',
    projectId: 'study-app-9988e',
    authDomain: 'study-app-9988e.firebaseapp.com',
    storageBucket: 'study-app-9988e.appspot.com',
    measurementId: 'G-TH6SWHLB50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYPCh-Vdfgx7HJiuJyV_E9V8VG1jXosM8',
    appId: '1:250155716405:android:e619167e64c11fb44e467c',
    messagingSenderId: '250155716405',
    projectId: 'study-app-9988e',
    storageBucket: 'study-app-9988e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDH0PXbYZzaJoOWXQmWiyaza_7iQA0FiU',
    appId: '1:250155716405:ios:aa24c82f027dc5c84e467c',
    messagingSenderId: '250155716405',
    projectId: 'study-app-9988e',
    storageBucket: 'study-app-9988e.appspot.com',
    iosClientId: '250155716405-5ua65ignf3h2jb2s38qpnsjpiuk32229.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDH0PXbYZzaJoOWXQmWiyaza_7iQA0FiU',
    appId: '1:250155716405:ios:aa24c82f027dc5c84e467c',
    messagingSenderId: '250155716405',
    projectId: 'study-app-9988e',
    storageBucket: 'study-app-9988e.appspot.com',
    iosClientId: '250155716405-5ua65ignf3h2jb2s38qpnsjpiuk32229.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
